export interface Tool {
  name: string;
  image: string;
}

export const tools: Tool[] = [
  { name: "Seller Central", image: "/amit-tiwari/tools/seller-central.png" },
  { name: "AppFollow", image: "/amit-tiwari/tools/appfollow.png" },
  { name: "Buffer", image: "/amit-tiwari/tools/buffer.png" },
  { name: "Canva", image: "/amit-tiwari/tools/canva.png" },
  { name: "CapCut", image: "/amit-tiwari/tools/capcut.png" },
  { name: "Carrd", image: "/amit-tiwari/tools/carrd.png" },
  { name: "ChatGPT", image: "/amit-tiwari/tools/chatgpt.png" },
  { name: "Claude", image: "/amit-tiwari/tools/claude.png" },
  { name: "Copy.ai", image: "/amit-tiwari/tools/copy-ai.png" },
  { name: "Elementor", image: "/amit-tiwari/tools/elementor.png" },
  { name: "Facebook", image: "/amit-tiwari/tools/facebook.png" },
  { name: "Fiverr", image: "/amit-tiwari/tools/fiverr.png" },
  { name: "Gemini", image: "/amit-tiwari/tools/gemini.png" },
  { name: "GoDaddy", image: "/amit-tiwari/tools/godaddy.png" },
  { name: "Google", image: "/amit-tiwari/tools/google.png" },
  { name: "Google Ads", image: "/amit-tiwari/tools/google-ads.png" },
  { name: "Google Alerts", image: "/amit-tiwari/tools/google-alerts.png" },
  { name: "Google Analytics", image: "/amit-tiwari/tools/google-analytics.png" },
  { name: "GMB", image: "/amit-tiwari/tools/gmb.png" },
  { name: "Google Docs", image: "/amit-tiwari/tools/google-docs.png" },
  { name: "Google Form", image: "/amit-tiwari/tools/google-form.png" },
  { name: "Keyword Planner", image: "/amit-tiwari/tools/keyword-planner.png" },
  { name: "Merchant Center", image: "/amit-tiwari/tools/merchant-center.png" },
  { name: "PageSpeed", image: "/amit-tiwari/tools/pagespeed.png" },
  { name: "Search Console", image: "/amit-tiwari/tools/search-console.png" },
  { name: "Google Slides", image: "/amit-tiwari/tools/google-slides.png" },
  { name: "Tag Manager", image: "/amit-tiwari/tools/tag-manager.png" },
  { name: "Trends", image: "/amit-tiwari/tools/trends.png" },
  { name: "GTmetrix", image: "/amit-tiwari/tools/gtmetrix.png" },
  { name: "Hostinger", image: "/amit-tiwari/tools/hostinger.png" },
  { name: "Hotjar", image: "/amit-tiwari/tools/hotjar.png" },
  { name: "HubSpot", image: "/amit-tiwari/tools/hubspot.png" },
  { name: "InShot", image: "/amit-tiwari/tools/inshot.png" },
  { name: "Instagram", image: "/amit-tiwari/tools/instagram.png" },
  { name: "Internshala", image: "/amit-tiwari/tools/internshala.png" },
  { name: "Jasper", image: "/amit-tiwari/tools/jasper.png" },
  { name: "LinkedIn", image: "/amit-tiwari/tools/linkedin.png" },
  { name: "Looker Studio", image: "/amit-tiwari/tools/looker-studio.png" },
  { name: "Mailchimp", image: "/amit-tiwari/tools/mailchimp.png" },
  { name: "Meta Ads", image: "/amit-tiwari/tools/meta-ads.png" },
  { name: "Meta", image: "/amit-tiwari/tools/meta.png" },
  { name: "Meta Suite", image: "/amit-tiwari/tools/meta-suite.png" },
  { name: "Miro", image: "/amit-tiwari/tools/miro.png" },
  { name: "Moz", image: "/amit-tiwari/tools/moz.png" },
  { name: "Notion", image: "/amit-tiwari/tools/notion.png" },
  { name: "Pinterest", image: "/amit-tiwari/tools/pinterest.png" },
  { name: "Quora", image: "/amit-tiwari/tools/quora.png" },
  { name: "SEMrush", image: "/amit-tiwari/tools/semrush.png" },
  { name: "Screaming Frog", image: "/amit-tiwari/tools/screaming-frog.png" },
  { name: "Shopify", image: "/amit-tiwari/tools/shopify.png" },
  { name: "Ubersuggest", image: "/amit-tiwari/tools/ubersuggest.png" },
  { name: "Unbounce", image: "/amit-tiwari/tools/unbounce.png" },
  { name: "Upwork", image: "/amit-tiwari/tools/upwork.png" },
  { name: "WhatsApp", image: "/amit-tiwari/tools/whatsapp.png" },
  { name: "WhatsApp Business", image: "/amit-tiwari/tools/whatsapp-business.png" },
  { name: "WordPress", image: "/amit-tiwari/tools/wordpress.png" },
  { name: "Yoast", image: "/amit-tiwari/tools/yoast.png" },
  { name: "YouTube", image: "/amit-tiwari/tools/youtube.png" },
];
